### ISSUE TITLE
K-NN searching not fully used  

### ISSUE THREAD

**Issue by exepulveda** [JuliaEarth/GeoStatsBase.jl#43] opened 2020-07-08 05:27 UTC
It seems in neighborsearch/neighborhood_searcher.jl there is space to improve k-nn efficiency.

Line 47: Instead of using inrange function of KDTree, one can use the function knn which searches for the k-th directly.

knn(tree, points, k, sortres = false, skip = always_false) -> idxs, dists

I'm not clear if this simple change may affect calling code to the function search!, therefore, I'm not requesting a pull request.
inrange search for all points within a radius, but for Kriging perspective, one needs just the k NN within the radius.

Another observation is that the knn function of the KDTree is not fully efficient because one can search using both parameters: k and radius to perform better. I will try to make a pull request to NearestNeighbors.jl project with this improvement.

**Comment by juliohm** [comment] 2020-07-08 10:49
That is amazing @exepulveda , certainly a great improvement to both projects. Could you please ping me in the NearestNeighbors.jl pull request? I am curious to learn about the improvement you mentioned.

I will double check the usage in neighborhood_search.jl meanwhile and digest your suggestion. :+1:

**Comment by juliohm** [comment] 2020-07-12 22:51
@exepulveda just so you understand the codebase, we have three types of neighborhood search currently implemented:

- [NearestNeighborSearcher](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/master/src/neighborsearch/nearest_searcher.jl)
- [NeighborhoodSearcher](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/master/src/neighborsearch/neighborhood_searcher.jl)
- [BoundedSearcher](https://github.com/JuliaEarth/GeoStatsBase.jl/blob/master/src/neighborsearch/bounded_searcher.jl)

The last type is a meta type that takes a searcher and bounds the number of neighbors to a maximum number. The first type uses the `knn` as you suggested (and is therefore very fast). The second type uses the `inrange` to find all points inside the ball.

We are currently using the second type in Kriging to update the conditional distribution iteratively each time a new point is added to the "estimated" set. Perhaps we could revisit this algorithm somehow and update the KDTree point by point if this is possible.

I am finishing a major refactoring of the codebase and will come back to this afterwards. Please let me know if you have questions.

**Comment by exepulveda** [comment] 2020-07-14 23:44
After thinking in the problem, it seems the solution is trivial. As the knn of locations limited by a radius is a subset of one with infinity radius, one can search for the knn, which is fast, and then the knn found can be filtered by the desired radius.
I just wonder if you have time to have a online chat for me to understand the project organisation and setup the developer environment and help with the code.

**Comment by juliohm** [comment] 2020-07-14 23:58
I think the main performance difference we are observing here is due to the fact that currently we are "fitting" the KDtree to the entire set of unknown locations, not just the samples. If we had "fit" the KDtree to just the samples, the `inrange` would be quite fast and retrieve only the points inside the radius. The problem is that as Kriging proceeds new estimated points become "samples" and so we would need to update the KDtree accordingly. I don't know if the data structure allows this kind of update though.

I am assuming that other libraries such as GSLIB do a similar approach by "fitting" a search tree to the entire set of unknown locations, but I didn't have a chance to take a look into their Fortran codebase.

Regarding the meeting, sure, let's do it! I will see how my agenda looks like on Friday, and we can setup a call to meetup and brainstorm this issue, what do you think? Meanwhile, you can check these instructions here to get the dev env up and running: https://juliaearth.github.io/GeoStats.jl/stable/contributing/#Code-contribution-1

I am finishing a minor release this week with some considerable (yet must needed) breaking changes. The plan is to release it by the end of the week. Today I finished with the coding/testing part. The rest of the week is about updating documentation.

**Comment by exepulveda** [comment] 2020-07-15 00:22
I see. Well, in Kriging you don't need to include to the KDTree the restimated unknown locations because estimations should not be included later as conditioning samples.

GSLIb does not use KDTree. It uses a SuperGrid strategy which is slower than KDTree.

Happy to meet you. I suggest to do it next week. I'm in Adelaide (GMT+10:30). Just drop me an email with any proposed time to exequiel.sepulvedaescobedo@adelaide.edu.au

Cheers

**Comment by juliohm** [comment] 2020-07-15 00:30
Nice, it makes total sense. I was confused by the conditional simulation approach and included the estimated locations in the set. If we just do the KDTree on the original set of samples we will get the same speed of the nearest neighbor search :+1: 

The only decision that remains is what to do when a ball has fewer than a minimum number of points. Should we skip the location and revisit later? I will try to prepare some code changes by next week for us to discuss. Will drop you an email.

**Comment by exepulveda** [comment] 2020-07-15 00:36
As I mentioned, searching for k-nn and ball can be done in two steps:

1. Searching for knn
2. Filtering by the ball

Step 1 is very efficient, and step 2 is in the worse case O(k)

**Comment by juliohm** [comment] 2020-07-15 00:47
I think I am getting your point. We can always search the K neighbors, and discard those outside the ball. If there are too few of them inside the ball, we relax the constraint and use all K.

**Comment by exepulveda** [comment] 2020-07-15 01:04
That should be a user option. Users usually want to control minimum number of samples. In mining applications this is called "multiple passes", which means, you first try find at least k_1-nn and if it fails, you try next to find at least k_2-nn, and so on. But I guess having minimum and maximum number of samples should be sufficient. If you find less that the minimum, that location should be masked as not estimated.

**Comment by juliohm** [comment] 2020-07-21 12:05
It was nice chatting with you yesterday @exepulveda , please feel free to submit a PR with the improvements.

I thought of a name, perhaps `KBallSearcher` would be ok? The filename could be `kball_searcher.jl` and this searcher would wrap the `NearestSearcher` and do the post-processing with the ball `isneighbor` function to discard points outside the ball.

**Comment by exepulveda** [comment] 2020-07-23 05:46
It was my pleasure. I think I have a first version. Probably I need to write some unit tests. Could you give me advise where to place the unit tests? I could not find any for the other searchers. 

Are you using a specific branch for developing in order to push my changes?

Cheers

**Comment by juliohm** [comment] 2020-07-23 10:46
> Could you give me advise where to place the unit tests? I could not find any for the other searchers.

You are right, we need unit tests for the searchers. They are being tested indirectly in downstream solvers, but we need to test them here as well. Could you please follow the pattern in the source code and create a file `test/neighborsearch.jl` with unit tests following the convention in `test/neighborhoods.jl` for example? That is, a `@testset` for each searcher. You don't need to bother about writing tests for the other existing searchers, but if you have time, that would be even nicer.

After you create this file, you just need to add it to the list in `test/runtests.jl`. To test locally, you can start Julia in the project folder with:
```
julia --project
```
and then type `] test`.

Also, something I forgot to share in our call, please take a look at the Revise.jl package, it can save a lot of time when you are in development mode: https://github.com/timholy/Revise.jl It will automatically detect changes in the source code and will recompile only the pieces you changed, so no need to restart or reload the package all the time. The only limitation is that it isn't able to track changes inside the struct definitions. If you change the fields of a struct during development you will need to restart the session.

> Are you using a specific branch for developing in order to push my changes?

Given that the project is still constantly evolving we are only using the master branch as our "dev" branch. Feel free to use any branch name to submit the PR. After we reach a first major release GeoStats.jl 1.0.0 we will need to rethink the development model, and follow something like the git flow.

**Comment by exepulveda** [comment] 2020-07-28 01:42
I will push to a new branch.
Including the new test I got: "Testing GeoStatsBase tests passed" :-)

**Comment by exepulveda** [comment] 2020-07-28 02:05
I'm having access problems when trying to push to (or create) a new branch. The error:

remote: Permission to JuliaEarth/KrigingEstimators.jl.git denied to exepulveda.

**Comment by juliohm** [comment] 2020-07-28 10:51
The GitHub workflow goes as follows:

1. Fork GeoStatsBase.jl on GitHub (there is a button at the top right of this repo)
2. Add a nickname to your fork in your local repo:

```
git remote add myfork URL-FOR-YOUR-GITHUB-FORK
```

This command is typed inside the `.julia/dev/GeoStatsBase` folder.

3. Push your changes to the fork:

```
git checkout mybranch
git push myfork
```

4. Go to your fork or to the original project page on GitHub, and GitHub will show you a banner asking if you want to create a PR.

The process is the same for KrigingEstimators.jl :+1:

**Comment by exepulveda** [comment] 2020-07-28 12:14
My bad. I forgot to fork instead cloning.

**Comment by juliohm** [comment] 2020-08-11 22:16
Closing this one as it is fixed on master :ok_hand:

**Closed by juliohm** 2020-08-11 22:16 UTC
